spring.application.name=CRUD-Read
spring.application.name=CRUD-Read-Mybatis

spring.datasource.url=jdbc:mysql://localhost:3306/your_database_name?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=JST


spring.datasource.username=tsuguchi


spring.datasource.password=tsuguchi


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


mybatis.configuration.map-underscore-to-camel-case=true
