spring.application.name=CRUD-Read-Mybatis
# ===============================
# ??????????
# ===============================
# ???URL: 'your_database_name' ??????????????????????????????
spring.datasource.url=jdbc:mysql://localhost:3306/your_database_name?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=JST

# ?????: MySQL???????????????: root?
spring.datasource.username=tsuguchi

# ?????: ????????????
spring.datasource.password=tsuguchi

# JDBC?????????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# MyBatis???????
# ===============================
# DB???????: user_name??Java?????????: userName??????????????
mybatis.configuration.map-underscore-to-camel-case=true
